### ISSUE TITLE
Copy to this repo

### ISSUE THREAD

**Issue by diasdavid** [inesc-id/hypercerts-pm#25]
Hey @joaosantos15, could you move https://docs.google.com/document/d/1yxFfmbNKNCmnzV0StFCnu93V6h7lPsc3cTXGCzxJIRM/edit#heading=h.tlhbjd3cfs63 to this repo as a markdown doc? Let's try to keep the house always tidy :)

**Comment by joaosantos15** [comment]
Hey, @diasdavid 
That gdocs document was just a draft, there is already a .md version [here](https://github.com/inesc-id/hypercerts-pm/blob/master/hypercerts-architecture.md) :)
